### ISSUE TITLE
Action Facade\Ignition\Http\Controllers\ShareReportController not defined.

### ISSUE THREAD

**Issue by whoami213** [facade/ignition#202] opened 2019-10-14 23:55 UTC
# Laravel Version:
 - 6.2.0
# Facade Ignition:
 - 1.6

# Problem:

not showing the UI of the Ignition.
problem with the ignition controller.

![image](https://user-images.githubusercontent.com/18107626/66790027-ac497d00-ef20-11e9-80eb-726615812c55.png)

**Comment by freekmurze** [comment] 2019-10-14 23:59
Could you try upgrading to the latest version of ignition and verify if the problem persist?

**Comment by julespeeters** [comment] 2019-10-15 07:10
+1 Using version 1.11.2. Probable cause in my case is using custom namespacing for all controllers as a result of a multi-tenant setup.

**Comment by whoami213** [comment] 2019-10-15 09:41
I'm using now 1.11.2, but the problem is still existing.
the error trigger here.
![image](https://user-images.githubusercontent.com/18107626/66820322-03783d80-ef73-11e9-991b-e6b6d53bf434.png)

**Comment by mpociot** [comment] 2019-10-15 10:04
Can you see if your routes are cached and try clearing that cache using `php artisan route:clear`?

**Comment by wimurk** [comment] 2019-10-15 10:12
It's not a problem with the version. As @mpociot suggested `php artisan route:clear` fixes the problem

**Comment by stefanbauer** [comment] 2019-10-15 12:57
I cannot confirm that this helps.

In my case, I use latest version of ignition and latest version of Laravel. What I do to produce the error:

- Use InertiaJS
- Add `Inertia::share()` in the `AppServiceProvider`
- Try to share something from the database, like `User::all()`

Then you get exactly what is reported in that issue here. If I remove exactly that one line of code, everything works well.

**Comment by whoami213** [comment] 2019-10-16 08:17
I have fixed my issue.

## Fixed:
I have a variable (holder for the database sharing data) on my blade template that doesn't exist, after deleting it was fixed.

## Issue:
Why is the Ignition Error handler not showing its UI? instead, it shows a non-related error to the main problem.

**Comment by DanielKeeble** [comment] 2019-10-16 14:11
I'm trying to update a Laravel 5.8 to Laravel 6 and am running into this issue. Had Ignition installed before the update and my test suite was running fine. Can't seem to figure out what is causing this.

**Comment by pxgamer** [comment] 2019-10-16 14:37
I think that this might be caused by the use of `$this->app->runningInConsole()` in:
https://github.com/facade/ignition/blob/39c02133b9803f892407a9790514a133a8f38986/src/IgnitionServiceProvider.php#L133-L135

When the routes are cached by `artisan route:cache`, it is running in console so I think they are excluded. Removing this seems to work, but not sure if this is really a fix. 🤔

**Comment by DanielKeeble** [comment] 2019-10-16 14:42
Good spot @pxgamer, I can confirm that is only an issue for me in `1.11.2` when this change was introduced. `1.11.1` works perfectly for me.

**Comment by wimurk** [comment] 2019-10-16 14:45
Probably why laravel uses `1.4` by default for it is tested on that version. I will wait for a stable release 👍

**Comment by DanielKeeble** [comment] 2019-10-16 14:46
I think `^1.4` will still resolve to the `1.11.2` release though.

**Comment by robmilward** [comment] 2019-10-16 22:14
So I ran into this same issue about an hour ago with an almost-fresh Laravel 6.0 app and have narrowed this down to: 

Any exception thrown before the application has finished booting, specifically, before the `IgnitionServiceProviders::registerHousekeepingRoutes` method is called, causes this error to be displayed via the default error renderer, _instead_ of the actual error via ignition.

You can replicate this issue by simply running `laravel new project` and adding a `throw new \Exception()` within the `register` method of the `AppServiceProvider`.

A simple POC fix can be done by modifying the `shareEndpoint` method within `vendor/facade/ignition/src/ErrorPage/ErrorPageViewModel.php`:
```php
protected function shareEndpoint()
{
    if (!app()->isBooted()) {
        return;
    }

    // use string notation as L5.5 and L5.6 don't support array notation yet
    return action('\Facade\Ignition\Http\Controllers\ShareReportController');
}
```

So... if the app isn't booted (and therefore routes aren't registered), don't attempt to rely on the URL generator to get the share endpoint for flare.

Returning nothing fixes the problem, but breaks the share functionality on the ignition page. I suppose the only real option is to hide the share feature when the endpoint can't be fetched.

**Comment by robmilward** [comment] 2019-10-16 22:44
So a little playing around with Ignition lead me down this potential path.

Within `vendor/facade/ignition/src/ErrorPage/ErrorPageViewModel.php` (I'm using the try-catch just to remain internally consistent):
```php
protected function shareEndpoint()
{
    try {
        // use string notation as L5.5 and L5.6 don't support array notation yet
        return action('\Facade\Ignition\Http\Controllers\ShareReportController');
    } catch (Exception $e) {
        return null;
    }
}
```

Within `vendor/facade/ignition/src/IgnitionConfig.php`:
```php
public function getEnableShareButton(): bool
{
    if (!app()->isBooted()) {
        return false;
    }

    return Arr::get($this->options, 'enable_share_button', true);
}
```

If the app isn't booted, I'm just using existing Ignition functionality to force-hide the share button.
Not entirely sure about this, nor am I sure how I'd test it just yet - it's late here though, I'll try to take another look tomorrow unless anyone else has any ideas. :clock12:

**Comment by stevebauman** [comment] 2019-10-17 04:24
Can confirm the above - v1.11.2 broke some of my tests. Downgrading to v1.11.1 fixed them.

**Comment by juanPao** [comment] 2019-10-20 09:29
Laravel Version:
6.0
Facade Ignition:
1.11.2

I'm still encountering this issue.
```
(1/1) InvalidArgumentException
Action Facade\Ignition\Http\Controllers\ShareReportController not define
```

**Comment by carlobeltrame** [comment] 2019-10-20 09:41
@juanPao See #204, the fix has not been merged yet.

**Comment by whoami213** [comment] 2019-10-21 08:45
This issue will be seen by using the `ddd()` function.

Moving forward.
is there any fixes merge?

**Comment by eaglearg** [comment] 2019-10-21 19:46
Please fix this, there is only problems  when you use route:cache. Thanks

**Comment by fosron** [comment] 2019-10-22 13:57
Laravel version: 6.3
Ignition version: 1.11.2

Just got this problem randomly while running PHPUnit test suite in a CI.

**Comment by lk77** [comment] 2019-10-23 08:20
Hello,

same issue here.

**Comment by stevebauman** [comment] 2019-10-23 13:16
@fosron At the time being you can target version v1.11.1 in your `composer.json` file and that resolved my issue with my tests - until the patched release is out.

**Comment by koenhendriks** [comment] 2019-11-02 20:19
@stevebauman I updated my composer but am still seeing this error in my Gitlab Runners... Also tried to clear the cache of the routes... still not working for me.

**Comment by stevebauman** [comment] 2019-11-02 20:43
@koenhendriks You may need to target an earlier version, such as v1.10.* as others have reported.

**Comment by sagargulati** [comment] 2019-11-06 18:59
So this doesn't work on facade/ignition (1.11.2)? I'm still seeing a symphony error page.

**Comment by yaroslavmo** [comment] 2019-11-07 10:41
Encountered this issue. Pretty strange that default Laravel 6 Ignition version comes with this problem. Hope it will be fixed soon!

**Comment by pxgamer** [comment] 2019-11-07 10:57
@sagargulati, this is waiting on #204 being reviewed and merged, so it is still an issue in 1.11.2, you can target `1.11.1` for now. Freek mentioned it would probably be merged and tagged "early next week" (this week), so shouldn't be too long. But I think they've been quite busy with MailCoach.

**Comment by sagargulati** [comment] 2019-11-07 11:51
Yeah, I downgraded to 1.11.1, and it worked fine. Looking forward to the update.
Thanks!

**Comment by ryryan** [comment] 2019-11-09 19:25
Fresh Laravel install (latest), this error occurs. Even after downgrading to 1.11.1 and verifying it has downgraded (cleared all routes and cache), it still throws this error.

**Comment by koenhendriks** [comment] 2019-11-09 20:19
Can confirm, same as @ryryan

**Comment by alkhachatryan** [comment] 2019-11-10 18:24
> Can you see if your routes are cached and try clearing that cache using `php artisan route:clear`?

Strange, the problem couldn't solve via PHP ARTISAN OPTIMIZE
And too strange, I still can use this command in NEW INSTALLED Laravel 6.*

**Comment by NathanD19** [comment] 2019-11-10 23:47
I can confirm after rolling back to 1.11.1, clearing cache, restarting server, I am still reciving this error.

**Comment by sigmoidal** [comment] 2019-11-11 20:57
I applied the proposed workaround by @robmilward on L6.5.0 with Ignition 1.11.2, but it does not fix it for me. Even downgrading to Ignition 1.11.1 did not fix it.

The problem came to be when I switched some routes in a custom package from using:
```
Route::group([], function() {
   Route::get('some_function',
              'MyVendor\MyPackage\App\Http\Controllers\MyController@some_function');
});
```

to enclose them in a Route::namespace, e.g.:
```
Route::namespace('MyVendor\MyPackage\App\Http\Controllers')->group([], function() {
   Route::get('some_function',
              'MyController@some_function');
});
```
when I switch between the two versions (and despite clearing all caches between changes) it consistently breaks with the namespace version.

**Comment by juanPao** [comment] 2019-11-12 06:48
try `php artisan route:clear` will temporary solve the problem

**Comment by phenix-factory** [comment] 2019-11-13 16:46
This error break some of my unit test. Are we close to fixing it ?

**Closed** 2019-11-14 10:27 UTC

**Comment by ttjordan81** [comment] 2019-11-18 21:38
I had the same issue, however, my issue started when I change my .env file from ("APP_ENV=local") to (APP_ENV="production"), then set APP_DEBUG=false. 

The one thing I didn't do was make sure all the dev composer packages were not installed... I re-ran (composer install --no-dev), which left out all the dev packages, then everything started working... Hope this helps someone!

**Comment by ignades** [comment] 2019-12-11 18:44
> It's not a problem with the version. As @mpociot suggested `php artisan route:clear` fixes the problem
> I normally do `php artisan optimize` but that doesn't clear the routes i think.
> 
> Also i use the version 1.4 like the laravel docs.
i have commented     // protected $casts = [
    //     'email_verified_at' => 'datetime',
    // ];
the field cant stay empty

**Comment by payamomrani** [comment] 2019-12-18 18:45
> Using **Laravel Framework 6.5.0**
> 
> I had the same issue, however, my issue started when I changed my .env file from ("APP_ENV=local") to (APP_ENV="production"), then set APP_DEBUG=false.
> 
> The one thing I didn't do was make sure all the dev composer packages were not installed... I re-ran (`composer install --no-dev`), which left out all the dev packages, then everything started working...
> 
> 1. `APP_ENV="production"`
> 2. `APP_DEBUG=false`
> 3. `composer install --no-dev; php artsian cache:clear; php artisan config:clear; php artisan view:clear; php artisan route:clear`
> 
> Hope this helps someone!

Thank you 
It Worked For Me

**Comment by payamomrani** [comment] 2019-12-19 13:39
> So a little playing around with Ignition lead me down this potential path.
> 
> Within `vendor/facade/ignition/src/ErrorPage/ErrorPageViewModel.php` (I'm using the try-catch just to remain internally consistent):
> 
> ```
> protected function shareEndpoint()
> {
>     try {
>         // use string notation as L5.5 and L5.6 don't support array notation yet
>         return action('\Facade\Ignition\Http\Controllers\ShareReportController');
>     } catch (Exception $e) {
>         return null;
>     }
> }
> ```
> 
> Within `vendor/facade/ignition/src/IgnitionConfig.php`:
> 
> ```
> public function getEnableShareButton(): bool
> {
>     if (!app()->isBooted()) {
>         return false;
>     }
> 
>     return Arr::get($this->options, 'enable_share_button', true);
> }
> ```
> 
> If the app isn't booted, I'm just using existing Ignition functionality to force-hide the share button.
> Not entirely sure about this, nor am I sure how I'd test it just yet - it's late here though, I'll try to take another look tomorrow unless anyone else has any ideas. 🕛

Thank you 
This fix my issue

**Comment by realtebo** [comment] 2020-03-05 11:13
I noticied that this errors happen every time I have a variable or a method undefined, not only in a blade but also in a controller, try for example to define a new route and do not create the controller's function

**Comment by Levivb** [comment] 2020-03-05 11:19
the problem is infacade/ignition/src/IgnitionServiceProvider.php:132 in method `registerHousekeepingRoutes`.

The check
```php
if ($this->app->runningInConsole()) {
            return $this;
        }
``` 
shouldn't be made

this means if you run `artisan route:cache`, the routes won't be registered in your app since it's a console command. Upon an error an attempt is made to show the ignition error page, but none of the routes it needs are registered, causing exceptions while showing the exception page.

My fix in my own `RouteServiceProvider` until this is fixed:
```php
    public function map(Router $router): void
    {
        parent::map($router);

        $this->registerIgnitionRoutes($router);
    }

private function registerIgnitionRoutes(Router $router): void
    {
        if ($this->app->routesAreCached()) {
            return;
        }

        if (
            !class_exists(HealthCheckController::class)
            || !class_exists(ExecuteSolutionController::class)
            || !class_exists(IgnitionConfigValueEnabled::class)
            || !class_exists(ShareReportController::class)
            || !class_exists(ScriptController::class)
        ) {
            return;
        }

        $router->group(
            [
                'prefix' => config('ignition.housekeeping_endpoint_prefix', '_ignition'),
                'middleware' => [IgnitionEnabled::class],
            ],
            static function (Router $router): void {
                $router->get('health-check', HealthCheckController::class);

                $router->post('execute-solution', ExecuteSolutionController::class)
                    ->middleware(IgnitionConfigValueEnabled::class . ':enableRunnableSolutions');

                $router->post('share-report', ShareReportController::class)
                    ->middleware(IgnitionConfigValueEnabled::class . ':enableShareButton');

                $router->get('scripts/{script}', ScriptController::class);
                $router->get('styles/{style}', StyleController::class);
            }
        );
    }
```

**Comment by ignades** [comment] 2020-03-05 12:48
Buon giorno Mirko, mi sà che hai sbagliato persona, non so a chi tu
abbia mandato questo messaggio ma di certo non sono io! Saluti!

Il
05.03.2020 12:13 Mirko Tebaldi ha scritto: 

> I noticied that this
errors happen every time I have a variable or a method undefined, not
only in a blade but also in a controller, try for example to define a
new route and do not create the controller's function 
> 
> --
> You are
receiving this because you commented.
> Reply to this email directly,
view it on GitHub [1], or unsubscribe [2].
  


Con Tiscali Mobile Smart 30 4G hai minuti illimitati, 100 SMS e 30 Giga in 4G a soli 8,99€ al mese. http://tisca.li/smart30

**Comment by realtebo** [comment] 2020-03-05 15:16
@ignades  you are subscribed to a github conversation, and so you received FROM GITHUB the email notification of my reply ... then you replied to github email, without reading it, and now the your very lol email is published on github....  

Please come online on github issue  linked above and remove your comment

https://github.com/facade/ignition/issues/202

Than please unsubscribe and or remove email notifications.

OMG, this was very funny-
