### ISSUE TITLE
Request not showing multi-dimensional information but [Object Object]

### ISSUE THREAD

**Issue by SebastianSchoeps** [facade/ignition#223] opened 2019-12-01 17:54 UTC
Hi,

it seems like when the request contains JSON it is not display correctly. The request is shown in Flare as:

```
Body
version   1.0
session   [object Object]
context   [object Object]
request   [object Object]
```

The request actually is:
```
{
    "version": "1.0",
    "session": {
        "new": false,
        "sessionId": "amzn1.echo-api.session.bb390424-e5ad-44f5-bc76-xxx",
        "application": {
            "applicationId": "amzn1.ask.skill.ca269bc6-15e7-4649-a565-xxx"
        },
        "user": {
            "userId": "amzn1.ask.account.xxx"
        }
    },
    "context": {
        "System": {
            "application": {
                "applicationId": "amzn1.ask.skill.ca269bc6-15e7-4649-a565-xxx"
            },
            "user": {
                "userId": "amzn1.ask.account.AFHMFQ5I4Bxxx"
            },
            "device": {
                "deviceId": "amzn1.ask.device.AG4DZEHxxx",
                "supportedInterfaces": []
            },
            "apiEndpoint": "https:\/\/api.eu.amazonalexa.com",
            "apiAccessToken": "eyJ0eXxxx"
        }
    },
    "request": {
        "type": "IntentRequest",
        "requestId": "amzn1.echo-api.request.89677478-03f3-401f-a17b-xxx",
        "timestamp": "2019-12-01T09:05:54Z",
        "locale": "de-DE",
        "intent": {
            "name": "BuyEpisodes",
            "confirmationStatus": "NONE"
        },
        "dialogState": "STARTED"
    }
}
```

Any chance to go multi-dimensional?

Thanks!
Sebastian

**Comment by Vinimaks** [comment] 2020-04-09 13:56
Are there any updates? I guess this issue is important

**Comment by brezzhnev** [comment] 2020-04-09 13:57
@freekmurze can you prioritize this issue, please? It's super valuable for us to have the actual request payload.

**Comment by AdrianMrn** [comment] 2020-04-10 10:51
I've pushed a fix for this to the Flare repo, it's Easter weekend right now so we might delay a deploy until early next week.

Please let me know if this fixes your issue and if any other issues arise. The fix should work retroactively: you should be able to see the request data of old occurrences.

**Comment by AdrianMrn** [comment] 2020-04-16 14:18
@brezzhnev @Vinimaks @SebastianSchoeps Can you check if the issue is solved for you?

**Closed** 2020-04-16 15:17 UTC
Labels: bug

**Comment by brezzhnev** [comment] 2020-04-20 15:11
@AdrianMrn kudos and tacos from me 👍👍
