### ISSUE TITLE
Allowed memory size of 1073741824 bytes exhausted (tried to allocate 33554440 bytes)

### ISSUE THREAD

**Issue by flysion** [facade/ignition#302] opened 2020-08-07 10:45 UTC
https://github.com/facade/ignition/blob/58dc4a8df3d41174c677a370b6779b694e4539e7/src/LogRecorder/LogRecorder.php#L35

When the code is running in console mode, this will cause the memory to continue to increase

**Comment by kktsvetkov** [comment] 2020-08-07 17:48
Can put some optional limit to the number of messages stored in `LogRecorder::$logMessages`, so when they are over the limit, the older messages are being discarded. However, I am not entirely sure how the garbage collection works and if the discarded objects will free their allocated memory

**Comment by TheLevti** [comment] 2021-01-16 19:26
Run into the same issue. There is currently no way to avoid the daemon to crash because at some point memory is full. I use for example Senty for exception reporting and their sdk also just tracks the last 100 events (logs) for example. It would be a good idea to limit this array to a maximum slots.

**Comment by TheLevti** [comment] 2021-01-17 14:28
Duplicate of #301

**Closed** 2021-02-05 12:51 UTC

**Comment by TheLevti** [comment] 2021-02-14 12:49
This needs another fix. See conversation in #344 

#354 should fix this bug.

**Comment by rubenvanassche** [comment] 2021-02-15 07:58
This should be fixed with version 2.5.12, thanks @TheLevti for the fix.

**Comment by andybobnewton** [comment] 2021-05-20 16:18
this doesn't seem to have done enough. the array has stopped increasing in size but the memory usage still goes up from just logging a string.

just running the below will increase memory usage until fatal error (about 6 seconds on machine). 

`
    while (true) {
        Log::debug("got message" );
    }
`
