### ISSUE TITLE
5.8 installations need later version

### ISSUE THREAD

**Issue by snapey** [facade/ignition#18] opened 2019-08-30 19:16 UTC
The documentation implies that adding to the Handler.php is not necessary for Laravel 5.8

This did not work for me.  I was on 5.8.27.  Adding the code to Handler worked.

Upgrading Laravel to 5.8.34 fixed the issue. Maybe the installation instructions needs to be specific about the 5.8 version (presumably >= 5.8.33)

**Comment by gbwashleybrown** [comment] 2019-08-30 22:45
I was on v5.8.32 and Ignition didn't work, neither with or without the handler method. I had to update...

**Comment by randymfournier** [comment] 2019-09-04 19:15
Worked fine for me I had to remove the filp/whoops package from composer first then it worked as advertised. Just thought I'd throw that out there incase someone forgot to remove that package.

**Comment by gbwashleybrown** [comment] 2019-09-05 09:41
@randymfournier No where does it state that you're supposed to remove it. I didn't, and after updating, it now works - with whoops installed.

**Comment by randymfournier** [comment] 2019-09-05 10:10
@gbwashleybrown I didnt say it stated that, I was just saying what worked for me sorry for helping lol.

**Comment by cgcullen** [comment] 2019-09-08 16:33
None of those suggestions work for me.  I can't get it to work with 5.8.35

**Comment by cgcullen** [comment] 2019-09-08 16:40
A reinstall fixed it

**Comment by freekmurze** [comment] 2019-10-17 07:23
Closing this as i cannot reproduce this. @snapey feel free to PR improvements to our docs here: https://github.com/facade/flare-docs

**Closed by freekmurze** 2019-10-17 07:23 UTC
Labels: documentation, enhancement
