### ISSUE TITLE
BladeSourceMapCompiler returns invalid markup when adding line numbers

### ISSUE THREAD

**Issue by dodomedia** [facade/ignition#193] opened 2019-10-10 19:09 UTC
The BladeSourceMapCompiler is responsible for adding "|---LINE:xxx---|" annotations to Blade markup by searching them with regex in the methods "addEchoLineNumbers" and "addStatementLineNumbers". The flag "PREG_OFFSET_CAPTURE" ensures that "insertLineNumberAtPosition" can insert the annotation at the offset returned by performing the regex.

However, when using german umlauts (and probably other special chars, too) this behavior does not work any longer and produces invalid markup, because the returned byte offset is incorrect.

For example, using the following the Blade template:

```
@extends('template')
Wäre es nicht schön, wenn die Tür schließt?
@foreach ($x as $y => $z)
    {{ $y }}: {{ $z }}
@endforeach
```

Will result in:

```
|---LINE:1---|@extends('template')
Wäre es nicht schön, wenn die Tür schließt?
@for|---LINE:3---|each ($x as $y => $z)
    {{ $|---LINE:4---|y }}: {{ $|---LINE:4---|z }}
@end|---LINE:5---|foreach
```

Ignition can display the correct error message and nobody would notice that something is wrong.
The error message displayed, is: "Undefined variable: x"

But adding the same sentence with german umlauts again results in an unexpected behavior.

Having the following Blade template:

```
@extends('template')
Wäre es nicht schön, wenn die Tür schließt?
Wäre es nicht schön, wenn die Tür schließt?
@foreach ($x as $y => $z)
    {{ $y }}: {{ $z }}
@endforeach
```

Now results in:

```
|---LINE:1---|@extends('template')
Wäre es nicht schön, wenn die Tür schließt?
Wäre es nicht schön, wenn die Tür schließt?
@foreach|---LINE:4---| ($x as $y => $z)
    {{ $y }}|---LINE:5---|: {{ $z }}|---LINE:5---|
@endfore|---LINE:6---|ach
```

Now, the Blade compiler can not parse the foreach statement and will produce the ErrorException "Undefined offset: 1", because the method "compileForeach" in the trait "CompilesLoops" assumes that there is content in the array "$matches". This array is filled by executing the regex for analyzing the expression within the foreach statement, which now for Blade appears to be empty and therefore is invalid (an empty foreach statement in a Blade template would produce the same error).

By adding the same sentence again we produce an faulty offset of chars which is enough to leave the "@foreach" keyword intact. The compiler now thinks there is an foreach statement without parameters. The umlauts cause an invalid byte offset and the amounts of characters used in the multibyte functions to set the annotation will insert it at the wrong place.

**Comment by ThibaudDauce** [comment] 2019-11-13 16:12
Hi,

I have the same problem with a `@foreach`: `($tickets |---LINE:93---|as $ticket)`

Since the `LINE` annotation is merged with the `as`, Blade cannot parse the `foreach` with the error "Undefined offset: 1" in `CompilesLoops.php:104`.

The error seems random, I just added a link to my layout header and the error appeared. If I remove the link, it's working. The added block is really simple:

```blade
<a href="{{ route('AdministrationCoupons::index') }}">
    Coupons
</a>
```

**Comment by dwightwatson** [comment] 2019-11-20 01:19
Yeah, I've come across a similar error a number of times since upgrading to Laravel 6. It's been doing my head in so finally decided to dig in and see what's going on.

```
ErrorException
Undefined offset: 1
```

Which appears to come from [`trim($matches[1])` in `CompilesLoops.php`](https://github.com/laravel/framework/blob/6.x/src/Illuminate/View/Compilers/Concerns/CompilesLoops.php#L85-L104).

When I actually dump out the expression, this is what I see that's caused the error:

```
"($nearestPlaces |---LINE:398---|as $place)"
```

Of course, that isn't actually what was in the Blade template - it's just `@foreach ($nearestPlaces as $place)`. After some digging I suspect it's Ignition that is inserting this `LINE:*` syntax in [`BladeSourceMapCompiler`](https://github.com/facade/ignition/blob/master/src/Views/Compilers/BladeSourceMapCompiler.php).

When I actually disable Ignition (either through uninstalling it or adding it to the `dont-discover` array, not sure if that's an easier way) then I actually get the correct underlying error. In this case it was simply an undefined variable error, but I'm sure it could have been other causes when I've run into it in the past.

```
ErrorException (E_ERROR)
Undefined variable: listing (View: ...)
```

So, somehow when an error occurs in a Blade view, Ignition seems to swallow it and then cause another Blade error because the source map compiler is injecting line numbers. It's odd to me though, because I don't get why Blade would be trying to render a view after an exception has already been thrown. I don't know enough about this feature works in Ignition though.

Unfortunately Googling "Laravel Undefined offset: 1" is so generic I'm sure many people facing this problem wont' discover this issue, or realise it's related to Ignition.

Happy to provide more debug information or anything else that could be helpful in resolving this.

**Comment by ThibaudDauce** [comment] 2019-11-25 14:17
Ping @freekmurze @mpociot 

### Description:

When using a specific number of non ASCII characters and in a view with an exception, Ignition fails to generate the correct source map and breaks the Blade compilation. The exception shown is `ErrorException:  Undefined offset: 1` in `vendor/laravel/framework/src/Illuminate/View/Compilers/Concerns/CompilesLoops.php:95` and not the correct exception thrown.

### Steps To Reproduce:

You can clone the repository https://github.com/ThibaudDauce/ignition-fails and go to `/failing_correct` and `/failing_incorrect`. The views are really simple and the only difference is one more non ASCII character (`à` here but it's working with any special character) in `failing_incorrect.blade.php`.

To illustrate the problem, here is the result of the source map generation from Ignition (you can see the same thing by going into `vendor/facade/ignition/src/Views/Compilers/BladeSourceMapCompiler.php` and adding a `dd($map)` line 11):

The correct version (it's not really correct but the correct exception is thrown and shown):

```
<!DOCTYPE html>
<html lang="|---LINE:2---|<?php echo e(str_replace('_', '-', app()->getLocale())); ?>">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>
    </head>
    <body>
        ààààààà
        <?php
  |---LINE:12---|          throw new Exception   
        ?>|---LINE:13---|

        <ul>
            @foreac|---LINE:16---|h ([1, 2, 3] as $i => $test)
                <li><?php echo e($tes|---LINE:17---|t); ?></li>
            <?php endfor; ?>|---LINE:18---|each
        </ul>
    </body>
</html>
```

If I had a single `à`, Ignition generates `@foreach|---LINE:16---| ([1, 2, 3] as $i => $test)` and Blade cannot parse the `@foreach` anymore.

**Comment by mpociot** [comment] 2019-11-25 14:49
Thanks for the reproducable repo @ThibaudDauce 
This issue is now fixed in the master branch. Once all tests have passed, I'll tag a new version

**Closed** 2019-11-25 14:49 UTC

**Comment by ThibaudDauce** [comment] 2019-11-25 14:50
Thanks a lot for your reactivity.
